# ruff: noqa: SLF001
"""Romanization-conditional surname table tests (surname_romanizations.csv).

The table gives each as-written spelling the share of its remap target's
surname mass it keeps when scored as a surname; the discount in
NameParsingService consumes it for single-token surname candidates. Rows are
generated by scripts/generate_surname_romanizations.py; column semantics are
documented in sinonym/data/README.md.
"""

import importlib.util
import types
from pathlib import Path

import pytest

from sinonym.chinese_names_data import CANTONESE_SURNAMES
from sinonym.resources import open_csv_reader
from sinonym.services.initialization import DataInitializationService
from sinonym.services.name_lookup import DOMINANT_CHINESE_SURNAME_FREQ_MIN, SurnameResolver
from tests._case_assertions import assert_normalized_name


def _load_generator_module():
    """Import the generator script by absolute path.

    Anchored at the repo root (``parents[1]``), not the CWD, and loaded via an
    import spec so the script's ``__main__`` guard does not run ``main()``.
    """
    script_path = Path(__file__).resolve().parents[1] / "scripts" / "generate_surname_romanizations.py"
    spec = importlib.util.spec_from_file_location("_gen_surname_romanizations", script_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_build_rows():
    """Import ``build_rows`` from the generator script by absolute path."""
    module = _load_generator_module()
    return module.build_rows


def test_table_keys_match_lookup_normalization(detector):
    """Every spelling must be a unique norm_light fixed point with a valid share.

    A spelling that norm_light rewrites can never be queried by the scoring
    discount. Penalty rows come in two kinds:

    - remap-only spellings (no as-written attestation) must stay out of the
      surname tables, so the scoring discount fires on their remapped target
      mass rather than being short-circuited by an attested-as-written entry;
    - Korean-dominant CANTONESE_SURNAMES keys trimmed from full share (e.g.
      jung, moon, im) stay attested as-written but must carry the *discounted*
      as-written mass directly (their surname frequency equals the penalty
      ppm, not the Mandarin target's full mass), so no extra discount is owed.
    """
    data = detector._data
    rows = list(open_csv_reader("surname_romanizations.csv"))
    assert len(rows) == 253
    spellings = [row["spelling"] for row in rows]
    assert len(set(spellings)) == len(spellings)
    for row in rows:
        spelling = row["spelling"]
        assert detector._normalizer.norm_light(spelling) == spelling
        share = float(row["target_share"])
        assert 0.0 < share <= 1.0
        if share < 1.0 and spelling in data.surnames:
            # Attested-but-trimmed penalty row: frequency must be the discounted
            # as-written mass (a rare Chinese surname), never the full target.
            assert data.get_surname_freq(spelling) == pytest.approx(
                float(row["surname_ppm_as_written"]),
            ), spelling


def test_surname_romanization_loader_rejects_invalid_target_share(monkeypatch):
    rows = [
        {
            "spelling": "bad",
            "mandarin_target": "wang",
            "surname_ppm_as_written": "1.0",
            "target_share": "0",
        },
    ]
    monkeypatch.setattr("sinonym.services.initialization.open_csv_reader", lambda _name: iter(rows))
    service = DataInitializationService.__new__(DataInitializationService)

    with pytest.raises(ValueError, match=r"row 2: target_share"):
        service._load_surname_romanizations()


def test_surname_romanization_loader_rejects_invalid_as_written_ppm(monkeypatch):
    rows = [
        {
            "spelling": "bad",
            "mandarin_target": "wang",
            "surname_ppm_as_written": "nan",
            "target_share": "1.0",
        },
    ]
    monkeypatch.setattr("sinonym.services.initialization.open_csv_reader", lambda _name: iter(rows))
    service = DataInitializationService.__new__(DataInitializationService)

    with pytest.raises(ValueError, match=r"row 2: surname_ppm_as_written"):
        service._load_surname_romanizations()


def test_discount_fires_for_remap_only_spellings(detector):
    """Spellings granted surname mass only via remapping lose ~4 log-units."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Fai") == pytest.approx(-4.0, abs=1e-6)
    assert service._surname_spelling_share_logp("Kung") == pytest.approx(-4.0, abs=1e-6)


def test_discount_skips_attested_as_written_spellings(detector):
    """Spellings attested as surname romanizations as-written keep full mass."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Hui") == 0.0
    assert service._surname_spelling_share_logp("Tong") == 0.0


def test_discount_skips_whitelisted_wade_giles_surnames(detector):
    """Curated WG/Taiwanese surname spellings carry the full target share."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Tsai") == 0.0
    assert service._surname_spelling_share_logp("Chuang") == 0.0


def test_full_share_rows_resolve_to_runtime_surname_mass(detector):
    """Full-share rows resolve to their as-written key with at least target mass.

    The parser's as-written key preference relies on initialization loading
    every full-share spelling into surname_frequencies with the mandarin
    target's mass (e.g. chien -> qian's 1864.96, not the remapped jian's
    208.64), so this asserts the invariant the preference depends on.
    """
    rows = list(open_csv_reader("surname_romanizations.csv"))
    full_share_rows = [row for row in rows if float(row["target_share"]) == 1.0]
    resolver = SurnameResolver(detector._data, detector._normalizer)

    assert full_share_rows
    for row in full_share_rows:
        spelling = row["spelling"]
        assert resolver.parser_frequency((spelling.title(),)) >= float(row["surname_ppm_as_written"]), spelling


def test_surname_lookup_key_resolves_as_written_vs_remapped(detector):
    """The shared resolver keeps the as-written key for rows/direct-mass, else remapped.

    'kuang' carries direct surname mass (234 ppm) with no romanization row and
    would remap to the unattested 'guang'; batch/routing evidence resolves it to
    its attested as-written key via this shared resolver.
    """
    data = detector._data
    # Direct mass, no table row -> as-written key.
    assert data.surname_lookup_key("kuang", "guang") == "kuang"
    assert data.get_surname_freq("kuang") > 0
    # Romanization-table penalty row, no direct light mass -> as-written key.
    assert data.surname_lookup_key("fai", "hui") == "fai"
    # Full-share table row -> as-written key.
    assert data.surname_lookup_key("chien", "jian") == "chien"
    # No row and no direct mass -> remapped key.
    assert data.surname_lookup_key("zzqq", "wang") == "wang"


def test_evidence_frequencies_use_as_written_resolution(detector):
    """Batch/routing evidence resolves a spelling exactly like the curated table.

    Penalty rows keep the discounted as-written mass instead of remapping into
    the target's full mass (fai must not inherit xu's 13,395 ppm through the
    fai -> hui remap), and full-share rows keep the mandarin target's mass even
    when the remapped form has incidental mass of its own (chien -> qian's
    1864.96, not jian's 208.64).
    """
    data = detector._data
    normalizer = detector._normalizer
    resolver = SurnameResolver(data, normalizer)

    def evidence_freq(token: str) -> float:
        return resolver.evidence_frequency(token)

    assert evidence_freq("fai") == pytest.approx(245.344)
    assert evidence_freq("chien") == pytest.approx(1864.9567)
    # spellings outside the table keep their attested as-written mass
    assert evidence_freq("cha") == pytest.approx(255.4735, abs=1e-3)


def test_surname_resolver_parser_answers_match_current_parser_policy(detector):
    """Resolver parser answers match the current parser-strict key policy."""
    data = detector._data
    normalizer = detector._normalizer
    resolver = SurnameResolver(data, normalizer)
    cases = [
        (("Fai",), "hui"),
        (("Chien",), "chien"),
        (("Cha",), "zha"),
        (("Kuang",), "kuang"),
        (("Ou", "Yang"), "ou yang"),
        (("zzqq",), "zzqq"),
    ]

    for tokens, expected_key in cases:
        assert resolver.parser_frequency(tokens) == data.get_surname_freq(expected_key)
        assert resolver.parser_logp(tokens, -123.0) == data.get_surname_logp(expected_key, -123.0)
        assert resolver.parser_rank(tokens, -1.0) == data.get_surname_rank(expected_key, -1.0)

    for tokens, expected_key in cases:
        if len(tokens) == 1:
            assert resolver.parser_is_surname(tokens) is data.is_surname(tokens[0], expected_key)

    assert resolver.parser_is_wade_giles_initial_remapped_surname("Kuang")
    assert not resolver.parser_is_wade_giles_initial_remapped_surname("Chien")


def test_surname_resolver_evidence_answers_match_current_evidence_policy(detector):
    """Resolver evidence answers match as-written batch/routing evidence semantics."""
    data = detector._data
    normalizer = detector._normalizer
    resolver = SurnameResolver(data, normalizer)

    for token in ["fai", "chien", "cha", "zzqq"]:
        light_key = normalizer.norm_light(token)
        expected_key = data.surname_lookup_key(normalizer.norm_light(token), normalizer.norm(token))
        assert resolver.evidence_span_key(token) == expected_key
        assert resolver.evidence_frequency(token) == data.get_surname_freq_as_written(expected_key)
        assert resolver.evidence_frequency_for_key(expected_key) == data.get_surname_freq_as_written(expected_key)
        assert resolver.evidence_is_surname(token) is data.is_surname(token, expected_key)
        assert resolver.spelling(token) == data.resolve_surname_spelling(light_key)
        assert resolver.spelling_for_light_key(light_key) == data.resolve_surname_spelling(light_key)

    assert resolver.evidence_frequency("fai") == pytest.approx(245.344)
    assert resolver.evidence_frequency("chien") == pytest.approx(1864.9567)
    assert resolver.evidence_frequency("cha") == pytest.approx(255.4735, abs=1e-3)
    assert not hasattr(resolver, "parser_key")
    assert not hasattr(resolver, "evidence_key")


def test_dominant_surname_detection_uses_as_written_evidence(detector):
    """Dominant-surname detection must not inherit parser remap target mass."""
    resolver = SurnameResolver(detector._data, detector._normalizer)

    assert resolver.parser_frequency(("fai",)) >= DOMINANT_CHINESE_SURNAME_FREQ_MIN
    assert resolver.evidence_frequency("fai") < DOMINANT_CHINESE_SURNAME_FREQ_MIN
    assert not resolver.evidence_is_dominant_surname("fai")
    assert resolver.evidence_is_dominant_surname("zhang")


def test_surname_group_strength_requires_han_provenance(detector):
    """Standalone pinyin must not be silently routed through Han-backed strength scoring."""
    with pytest.raises(ValueError, match="Han provenance"):
        detector._surname_group_strength(("che",))


def test_remap_only_surname_candidates_lose_to_attested_parses(detector):
    """End-to-end: the two eval cases the discount fixes.

    'fai' (-> hui, 13,395 ppm) and 'kung' (-> gong) previously outscored the
    attested as-written surnames 'leung' and 'kong'.
    """
    assert_normalized_name(detector, "Leung Ka Fai", (True, "Ka-Fai Leung"))
    assert_normalized_name(detector, "Kong Kung", (True, "Kung Kong"))


def test_generator_help_exits_before_regeneration(monkeypatch, capsys):
    """``--help`` must print usage without touching detector/data generation."""
    module = _load_generator_module()

    def fail_detector():
        pytest.fail("help should exit before constructing the detector")

    monkeypatch.setattr(module, "ChineseNameDetector", fail_detector)

    with pytest.raises(SystemExit) as exc_info:
        module.main(["--help"])

    assert exc_info.value.code == 0
    captured = capsys.readouterr()
    assert "usage:" in captured.out
    assert "surname_romanizations.csv" in captured.out
    assert captured.err == ""


def test_build_rows_full_share_resists_self_row_corruption(detector):
    """A corrupted as-written frequency must not feed back into its own row.

    ``build_rows`` reads ``detector._data``, which initialization builds partly
    *from* surname_romanizations.csv. For a full-share Cantonese spelling the
    generator reads the Mandarin *target* frequency (base familyname data), not
    the spelling's own frequency entry (which the CSV seeds), so corrupting the
    spelling's own frequency must not change the regenerated mass.
    """
    build_rows = _load_build_rows()
    real = detector._data

    # 'lee' -> 'li': the target key differs from the as-written key, so
    # corrupting 'lee' does not touch the target 'li' the generator reads.
    spelling = "lee"
    mandarin = CANTONESE_SURNAMES[spelling][0].lower()
    assert mandarin != spelling
    expected = round(real.surname_frequencies[mandarin], 4)

    corrupt_freqs = dict(real.surname_frequencies)
    corrupt_freqs[spelling] = 999_999.0  # simulate a corrupted committed value

    fake_data = types.SimpleNamespace(
        surname_frequencies=corrupt_freqs,
        given_names=real.given_names,
        surnames=real.surnames,
        surname_as_written_aliases=real.surname_as_written_aliases,
    )
    fake_detector = types.SimpleNamespace(_data=fake_data, _normalizer=detector._normalizer)

    rows = build_rows(fake_detector)
    lee_row = next(row for row in rows if row["spelling"] == spelling)

    assert lee_row["surname_ppm_as_written"] == expected
    assert lee_row["surname_ppm_as_written"] != 999_999.0
