# ruff: noqa: PLR2004, SLF001
"""Romanization-conditional surname table tests (surname_romanizations.csv).

The table gives each as-written spelling the share of its remap target's
surname mass it keeps when scored as a surname; the discount in
NameParsingService consumes it for single-token surname candidates. Rows are
generated by scripts/generate_surname_romanizations.py; column semantics are
documented in sinonym/data/README.md.
"""

import pytest

from sinonym.resources import open_csv_reader
from tests._case_assertions import assert_normalized_name


def test_table_keys_match_lookup_normalization(detector):
    """Every spelling must be a unique norm_light fixed point with a valid share.

    A spelling that norm_light rewrites can never be queried by the scoring
    discount; penalty rows that are attested as-written would contradict the
    surname tables the discount defers to.
    """
    rows = list(open_csv_reader("surname_romanizations.csv"))
    assert len(rows) > 200
    spellings = [row["spelling"] for row in rows]
    assert len(set(spellings)) == len(spellings)
    for row in rows:
        assert detector._normalizer.norm_light(row["spelling"]) == row["spelling"]
        assert 0.0 < float(row["target_share"]) <= 1.0
        if float(row["target_share"]) < 1.0:
            assert row["spelling"] not in detector._data.surnames


def test_discount_fires_for_remap_only_spellings(detector):
    """Spellings granted surname mass only via remapping lose ~4 log-units."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Fai") == pytest.approx(-4.0, abs=1e-6)
    assert service._surname_spelling_share_logp("Kung") == pytest.approx(-4.0, abs=1e-6)


def test_discount_skips_attested_as_written_spellings(detector):
    """Spellings attested as surname romanizations as-written keep full mass."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Hui") == 0.0
    assert service._surname_spelling_share_logp("Tong") == 0.0


def test_discount_skips_whitelisted_wade_giles_surnames(detector):
    """Curated WG/Taiwanese surname spellings carry the full target share."""
    service = detector._parsing_service
    assert service._surname_spelling_share_logp("Tsai") == 0.0
    assert service._surname_spelling_share_logp("Chuang") == 0.0


def test_remap_only_surname_candidates_lose_to_attested_parses(detector):
    """End-to-end: the two eval cases the discount fixes.

    'fai' (-> hui, 13,395 ppm) and 'kung' (-> gong) previously outscored the
    attested as-written surnames 'leung' and 'kong'.
    """
    assert_normalized_name(detector, "Leung Ka Fai", (True, "Ka-Fai Leung"))
    assert_normalized_name(detector, "Kong Kung", (True, "Kung Kong"))
