config_version: 0.0.1
model_variants:
  sinonym_v1:
    instance: sinonym.timo.interface.Instance
    prediction: sinonym.timo.interface.Prediction
    predictor: sinonym.timo.interface.Predictor
    predictor_config: sinonym.timo.interface.PredictorConfig
    artifacts_s3_path: null
    python_version: "3.10"
    cuda: False
    integration_test: sinonym.timo.integration_test.TestIntegration
    docker_run_commands: []
  sinonym_routing_v1:
    instance: sinonym.timo.interface.RoutingInstance
    prediction: sinonym.timo.interface.RoutedPaperPrediction
    predictor: sinonym.timo.interface.RoutingPredictor
    predictor_config: sinonym.timo.interface.PredictorConfig
    artifacts_s3_path: null
    python_version: "3.10"
    cuda: False
    integration_test: sinonym.timo.integration_test.TestRoutingIntegration
    docker_run_commands: []
  sinonym_v2:
    instance: sinonym.timo.interface.Instance
    prediction: sinonym.timo.interface.PredictionV2
    predictor: sinonym.timo.interface.PredictorV2
    predictor_config: sinonym.timo.interface.PredictorConfig
    artifacts_s3_path: null
    python_version: "3.10"
    cuda: False
    integration_test: sinonym.timo.integration_test.TestIntegrationV2
    docker_run_commands: []
  sinonym_routing_v2:
    instance: sinonym.timo.interface.RoutingInstance
    prediction: sinonym.timo.interface.RoutedPaperPredictionV2
    predictor: sinonym.timo.interface.RoutingPredictorV2
    predictor_config: sinonym.timo.interface.PredictorConfig
    artifacts_s3_path: null
    python_version: "3.10"
    cuda: False
    integration_test: sinonym.timo.integration_test.TestRoutingIntegrationV2
    docker_run_commands: []
