name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]  # Also run on direct pushes to main for consistency

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev

      - name: Build package (verify it builds)
        run: uv build

      - name: Check test status against baseline (118 failures expected)
        run: uv run python scripts/check_test_status.py

      - name: Test import after build
        run: |
          uv pip install --system dist/*.whl --force-reinstall
          cd /tmp
          python -c "import sys, sinonym, pypinyin; print('✓ Package imports successfully'); print('PY:', sys.executable); print('sinonym from:', sinonym.__file__); print('pypinyin OK:', pypinyin.__version__)"