name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]  # Also run on direct pushes to main for consistency

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint
        run: uv run ruff check .

      - name: Build package (verify it builds)
        run: uv build

      - name: Run tests (118 failures expected at baseline)
        run: uv run pytest tests/ -v || echo "Expected test failures - checking baseline with test status script"

      - name: Check test status against baseline
        run: uv run python scripts/check_test_status.py

      - name: Test import after build
        run: |
          uv pip install dist/*.whl --force-reinstall
          python -c "from sinonym import ChineseNameDetector; print('✓ Package imports successfully')"