name: Build and publish to PyPI

on:
  push:
    tags:
      - 'v*'    # publish on version tag pushes like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}